// Generated by SFHaxe 0.3.2
package sf.type;
extern class EffectData {
	/**
		SHARED
		 Sets the effect's start pos
		 Limited to world bounds (+-16386 on every axis) and has horrible networking precision. (17 bit float per component)
	**/
	@:native("setStart") public function setStart(start:sf.type.Vector):Void;
	/**
		SHARED
		 Sets the effect's color
		 Internally stored as an integer, but only first 8 bits are networked, effectively limiting this function to 0-255 range.
	**/
	@:native("setColor") public function setColor(color:Float):Void;
	/**
		SHARED
		 Sets the effect's angles
	**/
	@:native("setAngles") public function setAngles(ang:sf.type.Angle):Void;
	/**
		SHARED
		 Sets the effect's entity
	**/
	@:native("setEntity") public function setEntity(ent:sf.type.Entity):Void;
	/**
		SHARED
		 Sets the effect's flags
	**/
	@:native("setFlags") public function setFlags(flags:Float):Void;
	/**
		SHARED
		 Sets the effect's attachment
	**/
	@:native("setAttachment") public function setAttachment(attachment:Float):Void;
	/**
		SHARED
		 Sets the effect's scale
	**/
	@:native("setScale") public function setScale(scale:Float):Void;
	/**
		SHARED
		 Returns the effect's radius
	**/
	@:native("getRadius") public function getRadius():Float;
	/**
		SHARED
		 Sets the effect's origin
	**/
	@:native("setOrigin") public function setOrigin(origin:sf.type.Vector):Void;
	/**
		SHARED
		 Sets the effect's entity index
	**/
	@:native("setEntIndex") public function setEntIndex(index:Float):Void;
	/**
		SHARED
		 Sets the effect's material index
	**/
	@:native("setMaterialIndex") public function setMaterialIndex(mat:Float):Void;
	/**
		SHARED
		 Sets the effect's normal
	**/
	@:native("setNormal") public function setNormal(normal:sf.type.Vector):Void;
	/**
		SHARED
		 Sets the effect's damage type
	**/
	@:native("setDamageType") public function setDamageType(dmgtype:Float):Void;
	/**
		SHARED
		 Returns the effect's start position
	**/
	@:native("getStart") public function getStart():sf.type.Vector;
	/**
		SHARED
		 Returns byte which represents the color of the effect.
	**/
	@:native("getColor") public function getColor():Float;
	/**
		SHARED
		 Returns the effect's hitbox ID
	**/
	@:native("getHitBox") public function getHitBox():Float;
	/**
		SHARED
		 Sets the effect's magnitude
	**/
	@:native("setMagnitude") public function setMagnitude(magnitude:Float):Void;
	/**
		SHARED
		 Sets the effect's surface property
		 Internally stored as an integer, but only first 8 bits are networked, effectively limiting this function to -1-254 range.(yes, that's not a mistake)
	**/
	@:native("setSurfaceProp") public function setSurfaceProp(prop:Float):Void;
	/**
		SHARED
		 Returns the effect's flags
	**/
	@:native("getFlags") public function getFlags():Float;
	/**
		SHARED
		 Returns the effect's scale
	**/
	@:native("getScale") public function getScale():Float;
	/**
		SHARED
		 Sets the effect's radius
	**/
	@:native("setRadius") public function setRadius(radius:Float):Void;
	/**
		SHARED
		 Plays the effect
	**/
	@:native("play") public function play(eff:std.String):Void;
	/**
		SHARED
		 Returns the effect's material index
	**/
	@:native("getMaterialIndex") public function getMaterialIndex():Float;
	/**
		SHARED
		 Returns the effect's angle
	**/
	@:native("getAngles") public function getAngles():sf.type.Angle;
	/**
		SHARED
		 Returns the effect's attachment
	**/
	@:native("getAttachment") public function getAttachment():Float;
	/**
		SHARED
		 Returns the effect's entity
	**/
	@:native("getEntity") public function getEntity():sf.type.Entity;
	/**
		SHARED
		 Sets the effect's hitbox
	**/
	@:native("setHitBox") public function setHitBox(hitbox:Float):Void;
	/**
		SHARED
		 Returns the effect's surface prop
	**/
	@:native("getSurfaceProp") public function getSurfaceProp():Float;
	/**
		SHARED
		 Returns the effect's magnitude
	**/
	@:native("getMagnitude") public function getMagnitude():Float;
	/**
		SHARED
		 Returns the effect's origin
	**/
	@:native("getOrigin") public function getOrigin():sf.type.Vector;
	/**
		SHARED
		 Returns the effect's normal
	**/
	@:native("getNormal") public function getNormal():sf.type.Vector;
	/**
		SHARED
		 Returns the effect's entindex
	**/
	@:native("getEntIndex") public function getEntIndex():Float;
	/**
		SHARED
		 Returns the effect's damagetype
	**/
	@:native("getDamageType") public function getDamageType():Float;
}

@:forward
extern abstract Effect(EffectData) {
}

