// Generated by SFHaxe 0.2.0
package sf.type;
extern class LightData {
	/**
		CLIENT
		 Sets whether the light should cast onto the world or not
	**/
	#if CLIENT @:native("setNoWorld") public function setNoWorld(on:Any):Void;#end
	/**
		CLIENT
		 Sets the light outer angle (used with setDirection and setInnerAngle)
	**/
	#if CLIENT @:native("setOuterAngle") public function setOuterAngle(ang:Any):Void;#end
	/**
		CLIENT
		 Sets the light inner angle (used with setDirection and setOuterAngle)
	**/
	#if CLIENT @:native("setInnerAngle") public function setInnerAngle(ang:Any):Void;#end
	/**
		CLIENT
		 Sets the flicker style of the light https://developer.valvesoftware.com/wiki/Light_dynamic#Appearances
	**/
	#if CLIENT @:native("setStyle") public function setStyle(style:Any):Void;#end
	/**
		CLIENT
		 Sets the color of the light
	**/
	#if CLIENT @:native("setColor") public function setColor(color:Any):Void;#end
	/**
		CLIENT
		 Sets the light brightness
	**/
	#if CLIENT @:native("setBrightness") public function setBrightness(brightness:Any):Void;#end
	/**
		CLIENT
		 Sets the light lifespan (Required for fade effect i.e. decay)
	**/
	#if CLIENT @:native("setDieTime") public function setDieTime(dietime:Any):Void;#end
	/**
		CLIENT
		 Draws the light. Typically used in the think hook. Will throw an error if it fails (use pcall)
	**/
	#if CLIENT @:native("draw") public function draw():Void;#end
	/**
		CLIENT
		 Sets the size of the light (max is sf_light_maxsize)
	**/
	#if CLIENT @:native("setSize") public function setSize(size:Any):Void;#end
	/**
		CLIENT
		 Sets the minimum light amount
	**/
	#if CLIENT @:native("setMinLight") public function setMinLight(min:Any):Void;#end
	/**
		CLIENT
		 Sets the light decay speed in thousandths per second. 1000 lasts for 1 second, 2000 lasts for 0.5 seconds
	**/
	#if CLIENT @:native("setDecay") public function setDecay(decay:Any):Void;#end
	/**
		CLIENT
		 Sets the light position
	**/
	#if CLIENT @:native("setPos") public function setPos(pos:Any):Void;#end
	/**
		CLIENT
		 Sets whether the light should cast onto models or not
	**/
	#if CLIENT @:native("setNoModel") public function setNoModel(on:Any):Void;#end
	/**
		CLIENT
		 Sets the light direction (used with setInnerAngle and setOuterAngle)
	**/
	#if CLIENT @:native("setDirection") public function setDirection(dir:Any):Void;#end
}

@:forward
extern abstract Light(LightData) {
}

