// Generated by SFHaxe 0.2.0
package sf.type;
extern class MarkupData {
	/**
		CLIENT
		 Get the object size
	**/
	#if CLIENT @:native("getSize") public function getSize():Any;#end
	/**
		CLIENT
		 Draw the markup object
	**/
	#if CLIENT @:native("draw") public function draw(x:Any, y:Any, xalign:Any, yalign:Any, a:Any):Void;#end
	/**
		CLIENT
		 Get the object width
	**/
	#if CLIENT @:native("getWidth") public function getWidth():Any;#end
	/**
		CLIENT
		 Get the object height
	**/
	#if CLIENT @:native("getHeight") public function getHeight():Any;#end
}

@:forward
extern abstract Markup(MarkupData) {
}

