// Generated by SFHaxe 0.2.0
package sf.type;
extern class MaterialData {
	/**
		CLIENT
		 Returns a float keyvalue
	**/
	#if CLIENT @:native("getFloat") public function getFloat(key:Any):Any;#end
	/**
		CLIENT
		 Refreshes the material. Sometimes needed for certain parameters to update
	**/
	#if CLIENT @:native("recompute") public function recompute():Void;#end
	/**
		CLIENT
		 Returns a matrix keyvalue
	**/
	#if CLIENT @:native("getMatrix") public function getMatrix(key:Any):Any;#end
	/**
		CLIENT
		 Returns a color pixel value of the $basetexture of a .png or .jpg material.
	**/
	#if CLIENT @:native("getColor") public function getColor(x:Any, y:Any):Any;#end
	/**
		CLIENT
		 Returns an int keyvalue
	**/
	#if CLIENT @:native("getInt") public function getInt(key:Any):Any;#end
	/**
		CLIENT
		 Sets an int keyvalue
	**/
	#if CLIENT @:native("setInt") public function setInt(key:Any, v:Any):Void;#end
	/**
		CLIENT
		 Returns a texture id keyvalue
	**/
	#if CLIENT @:native("getTexture") public function getTexture(key:Any):Any;#end
	/**
		CLIENT
		 Sets a float keyvalue
	**/
	#if CLIENT @:native("setFloat") public function setFloat(key:Any, v:Any):Void;#end
	/**
		CLIENT
		 Loads an online image or base64 data to the specified texture key
		 If the texture in key is not set to a rendertarget, a rendertarget will be created and used.
	**/
	#if CLIENT @:native("setTextureURL") public function setTextureURL(key:Any, url:Any, cb:Any, done:Any):Void;#end
	/**
		CLIENT
		 Returns a string keyvalue
	**/
	#if CLIENT @:native("getString") public function getString(key:Any):Any;#end
	/**
		CLIENT
		 Gets the base texture set to the material's width
	**/
	#if CLIENT @:native("getWidth") public function getWidth():Any;#end
	/**
		CLIENT
		 Returns a linear color-corrected vector keyvalue
	**/
	#if CLIENT @:native("getVectorLinear") public function getVectorLinear(key:Any):Any;#end
	/**
		CLIENT
		 Sets a texture keyvalue
	**/
	#if CLIENT @:native("setTexture") public function setTexture(key:Any, v:Any):Void;#end
	/**
		CLIENT
		 Returns a table of material keyvalues
	**/
	#if CLIENT @:native("getKeyValues") public function getKeyValues():Any;#end
	/**
		CLIENT
		 Returns the material's engine name
	**/
	#if CLIENT @:native("getName") public function getName():Any;#end
	/**
		CLIENT
		 Free's a user created material allowing you to create others
	**/
	#if CLIENT @:native("destroy") public function destroy():Void;#end
	/**
		CLIENT
		 Sets a vector keyvalue
	**/
	#if CLIENT @:native("setVector") public function setVector(key:Any, v:Any):Void;#end
	/**
		CLIENT
		 Sets a string keyvalue
	**/
	#if CLIENT @:native("setString") public function setString(key:Any, v:Any):Void;#end
	/**
		CLIENT
		 Sets a matrix keyvalue
	**/
	#if CLIENT @:native("setMatrix") public function setMatrix(key:Any, v:Any):Void;#end
	/**
		CLIENT
		 Returns the shader name of the material
	**/
	#if CLIENT @:native("getShader") public function getShader():Any;#end
	/**
		CLIENT
		 Returns a vector keyvalue
	**/
	#if CLIENT @:native("getVector") public function getVector(key:Any):Any;#end
	/**
		CLIENT
		 Sets a rendertarget texture to the specified texture key
	**/
	#if CLIENT @:native("setTextureRenderTarget") public function setTextureRenderTarget(key:Any, name:Any):Void;#end
	/**
		CLIENT
		 Sets a keyvalue to be undefined
	**/
	#if CLIENT @:native("setUndefined") public function setUndefined(key:Any):Void;#end
	/**
		CLIENT
		 Gets the base texture set to the material's height
	**/
	#if CLIENT @:native("getHeight") public function getHeight():Any;#end
}

@:forward
extern abstract Material(MaterialData) {
}

