// Generated by SFHaxe 0.2.0
package sf.type;
extern class NpcData {
	/**
		SERVER
		 Stops the npc
	**/
	#if SERVER @:native("stop") public function stop():Void;#end
	/**
		SERVER
		 Makes the npc run to a destination
	**/
	#if SERVER @:native("goRun") public function goRun(vec:Any):Void;#end
	/**
		SERVER
		 Makes the npc do a ranged attack
	**/
	#if SERVER @:native("attackRange") public function attackRange():Void;#end
	/**
		SERVER
		 Adds a relationship to the npc
	**/
	#if SERVER @:native("addRelationship") public function addRelationship(str:Any):Void;#end
	/**
		SERVER
		 Gives the npc a weapon
	**/
	#if SERVER @:native("giveWeapon") public function giveWeapon(wep:Any):Void;#end
	/**
		SERVER
		 Makes the npc do a melee attack
	**/
	#if SERVER @:native("attackMelee") public function attackMelee():Void;#end
	/**
		SERVER
		 Gets what the npc is fighting
	**/
	#if SERVER @:native("getEnemy") public function getEnemy():Any;#end
	/**
		SERVER
		 Makes the npc walk to a destination
	**/
	#if SERVER @:native("goWalk") public function goWalk(vec:Any):Void;#end
	/**
		SERVER
		 Gets the npc's relationship to the target
	**/
	#if SERVER @:native("getRelationship") public function getRelationship(ent:Any):Any;#end
	/**
		SERVER
		 Adds a relationship to the npc with an entity
	**/
	#if SERVER @:native("addEntityRelationship") public function addEntityRelationship(ent:Any, disp:Any, priority:Any):Void;#end
	/**
		SERVER
		 Tell the npc to fight this
	**/
	#if SERVER @:native("setEnemy") public function setEnemy(ent:Any):Void;#end
}

@:forward
extern abstract Npc(NpcData) {
}

