// Generated by SFHaxe 0.2.0
package sf.type;
extern class ParticleData {
	/**
		CLIENT
		 Sets the velocity of the particle.
	**/
	#if CLIENT @:native("setVelocity") public function setVelocity(vel:Any):Void;#end
	/**
		CLIENT
		 Sets the angular velocity of the the particle.
	**/
	#if CLIENT @:native("setAngleVelocity") public function setAngleVelocity(angVel:Any):Void;#end
	/**
		CLIENT
		 Sets the material of the particle.
	**/
	#if CLIENT @:native("setMaterial") public function setMaterial(mat:Any):Void;#end
	/**
		CLIENT
		 Returns the current orientation of the particle.
	**/
	#if CLIENT @:native("getAngles") public function getAngles():Any;#end
	/**
		CLIENT
		 Scales the velocity based on the particle speed.
	**/
	#if CLIENT @:native("setVelocityScale") public function setVelocityScale(doScale:Any):Void;#end
	/**
		CLIENT
		 Sets the absolute position of the particle.
	**/
	#if CLIENT @:native("setPos") public function setPos(pos:Any):Void;#end
	/**
		CLIENT
		 Returns the current rotation of the particle in radians, this should only be used for 2D particles.
	**/
	#if CLIENT @:native("getRoll") public function getRoll():Any;#end
	/**
		CLIENT
		 Sets the directional gravity aka. acceleration of the particle.
	**/
	#if CLIENT @:native("setGravity") public function setGravity(gravity:Any):Void;#end
	/**
		CLIENT
		 Returns the angular velocity of the particle
	**/
	#if CLIENT @:native("getAngleVelocity") public function getAngleVelocity():Any;#end
	/**
		CLIENT
		 Sets the color of the particle.
	**/
	#if CLIENT @:native("setColor") public function setColor(col:Any):Void;#end
	/**
		CLIENT
		 Sets the angles of the particle.
	**/
	#if CLIENT @:native("setAngles") public function setAngles(ang:Any):Void;#end
	/**
		CLIENT
		 Returns the current velocity of the particle.
	**/
	#if CLIENT @:native("getVelocity") public function getVelocity():Any;#end
	/**
		CLIENT
		 Sets the rotation speed of the particle in radians. This should only be used for 2D particles.
	**/
	#if CLIENT @:native("setRollDelta") public function setRollDelta(rollDelta:Any):Void;#end
	/**
		CLIENT
		 Sets the air resistance of the the particle.
	**/
	#if CLIENT @:native("setAirResistance") public function setAirResistance(airResistance:Any):Void;#end
	/**
		CLIENT
		 Sets the 'bounciness' of the the particle.
	**/
	#if CLIENT @:native("setBounce") public function setBounce(bounce:Any):Void;#end
	/**
		CLIENT
		 Sets the roll of the particle in radians. This should only be used for 2D particles.
	**/
	#if CLIENT @:native("setRoll") public function setRoll(roll:Any):Void;#end
	/**
		CLIENT
		 Returns the color of the particle.
	**/
	#if CLIENT @:native("getColor") public function getColor():Any;#end
	/**
		CLIENT
		 Sets whether the particle should be affected by lighting.
	**/
	#if CLIENT @:native("setLighting") public function setLighting(useLighting:Any):Void;#end
	/**
		CLIENT
		 Sets the whether the particle should collide with the world or not.
	**/
	#if CLIENT @:native("setCollide") public function setCollide(shouldCollide:Any):Void;#end
	/**
		CLIENT
		 Returns the absolute position of the particle.
	**/
	#if CLIENT @:native("getPos") public function getPos():Any;#end
}

@:forward
extern abstract Particle(ParticleData) {
}

