// Generated by SFHaxe 0.3.3
package sf.type;
extern class SurfaceInfoData {
	/**
		SHARED
		Returns a list of vertices the brush surface is built from.
	**/
	@:native("getVertices") public function getVertices():lua.Table<Dynamic,Dynamic>;
	/**
		SHARED
		Checks if the brush surface is a nodraw surface, meaning it will not be drawn by the engine.
		This internally checks the SURFDRAW_NODRAW flag.
	**/
	@:native("isNoDraw") public function isNoDraw():Bool;
	/**
		SHARED
		Checks if the brush surface is displaying the skybox.
		This internally checks the SURFDRAW_SKY flag.
	**/
	@:native("isSky") public function isSky():Bool;
	/**
		SHARED
		Checks if the brush surface is water.
		This internally checks the SURFDRAW_WATER flag.
	**/
	@:native("isWater") public function isWater():Bool;
	/**
		SHARED
		Returns the brush surface's material.
	**/
	@:native("getMaterial") public function getMaterial():Dynamic;
}

@:forward
extern abstract SurfaceInfo(SurfaceInfoData) {
}

