// Generated by SFHaxe 0.2.0
package sf.type;
extern class VehicleData {
	/**
		SERVER
		 Returns the driver of the vehicle
	**/
	#if SERVER @:native("getDriver") public function getDriver():Any;#end
	/**
		SERVER
		 Returns a passenger of a vehicle
	**/
	#if SERVER @:native("getPassenger") public function getPassenger(n:Any):Any;#end
	/**
		SERVER
		 Ejects the driver of the vehicle
	**/
	#if SERVER @:native("ejectDriver") public function ejectDriver():Void;#end
	/**
		SERVER
		 Will unlock the vehicle.
	**/
	#if SERVER @:native("unlock") public function unlock():Void;#end
	/**
		SERVER
		 Will lock the vehicle preventing players from entering or exiting the vehicle.
	**/
	#if SERVER @:native("lock") public function lock():Void;#end
	/**
		SERVER
		 Kills the driver of the vehicle
	**/
	#if SERVER @:native("killDriver") public function killDriver():Void;#end
	/**
		SERVER
		 Strips weapons of the driver
	**/
	#if SERVER @:native("stripDriver") public function stripDriver(_class:Any):Void;#end
}

@:forward
extern abstract Vehicle(VehicleData) {
}

