// Generated by SFHaxe 0.3.0
package sf.type;
extern class VehicleData {
	/**
		SERVER
		 Returns the driver of the vehicle
	**/
	#if SERVER @:native("getDriver") public function getDriver():sf.type.Player;#end
	/**
		SERVER
		 Returns a passenger of a vehicle
	**/
	#if SERVER @:native("getPassenger") public function getPassenger(n:Float):sf.type.Player;#end
	/**
		SHARED
		 Turns a vehicle into a string.
	**/
	@:native("__tostring") public function __tostring():std.String;
	/**
		SERVER
		 Will unlock the vehicle.
	**/
	#if SERVER @:native("unlock") public function unlock():Void;#end
	/**
		SERVER
		 Will lock the vehicle preventing players from entering or exiting the vehicle.
	**/
	#if SERVER @:native("lock") public function lock():Void;#end
	/**
		SERVER
		 Ejects the driver of the vehicle
	**/
	#if SERVER @:native("ejectDriver") public function ejectDriver():Void;#end
	/**
		SERVER
		 Kills the driver of the vehicle
	**/
	#if SERVER @:native("killDriver") public function killDriver():Void;#end
	/**
		SERVER
		 Strips weapons of the driver
	**/
	#if SERVER @:native("stripDriver") public function stripDriver(?_class:Null<std.String>):Void;#end
}

@:forward
extern abstract Vehicle(VehicleData) {
}

