// Generated by SFHaxe 0.2.0
package sf.type;
extern class WirelinkData {
	/**
		SERVER
		 Checks if an input is wired.
	**/
	#if SERVER @:native("isWired") public function isWired(name:Any):Void;#end
	/**
		SERVER
		 Returns the entity that the wirelink represents
	**/
	#if SERVER @:native("entity") public function entity():Void;#end
	/**
		SERVER
		 Returns the name of the output an input of the wirelink is wired to.
	**/
	#if SERVER @:native("getWiredToName") public function getWiredToName(name:Any):Any;#end
	/**
		SERVER
		 Returns a table of all of the wirelink's outputs
	**/
	#if SERVER @:native("outputs") public function outputs():Void;#end
	/**
		SERVER
		 Returns the type of input name, or nil if it doesn't exist
	**/
	#if SERVER @:native("inputType") public function inputType():Void;#end
	/**
		SERVER
		 Returns the type of output name, or nil if it doesn't exist
	**/
	#if SERVER @:native("outputType") public function outputType():Void;#end
	/**
		SERVER
		 Checks if a wirelink is valid. (ie. doesn't point to an invalid entity)
	**/
	#if SERVER @:native("isValid") public function isValid():Void;#end
	/**
		SERVER
		 Returns what an input of the wirelink is wired to.
	**/
	#if SERVER @:native("getWiredTo") public function getWiredTo(name:Any):Any;#end
	/**
		SERVER
		 Returns a table of all of the wirelink's inputs
	**/
	#if SERVER @:native("inputs") public function inputs():Void;#end
}

@:forward
extern abstract Wirelink(WirelinkData) {
	/**
		SERVER
		 Writes to an input.
	**/
	@:op([]) public function __newindex(A:Any, B:Any):Any;
	/**
		SERVER
		 Retrieves an output. Returns nil if the output doesn't exist.
	**/
	@:op([]) public function __index(A:Any):Any;
}

